version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

    groups:
      dotnet-runtime-packages:
        patterns:
          - "Microsoft.Extensions.*"
          - "System.Diagnostics.EventLog"
          - "System.Configuration.ConfigurationManager"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10